name: dart2019
description: Advent of Code 2019 using Dart
version: 0.1.1
homepage: https://www.github.com/alomew/aoc/twentynineteen
author: alomew <alomew@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0